import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, CheckCircle2, ChevronDown, ExternalLink, FileSearch, LoaderCircle, RefreshCw, ShieldAlert, Sparkles, TrendingDown, TrendingUp } from 'lucide-react';
import type { ReactNode } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { fetchAudit, fetchAudits, rerunAudit } from '../features/audits/audit-api';
import { AuditFailure, AuditStatusBadge } from '../features/audits/audit-status';
import type { AuditIssue, AuditSeverity, WebsiteAudit } from '../features/audits/audit-types';
import { getApiError } from '../lib/api';

const scoreFields = [['Overall', 'overallScore'], ['Technical', 'technicalScore'], ['Performance', 'performanceScore'], ['SEO', 'seoScore'], ['Conversion', 'conversionScore'], ['Mobile', 'mobileScore']] as const;
const severityOrder: AuditSeverity[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'];

export function AuditDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const qc = useQueryClient();
  const query = useQuery({ queryKey: ['audit', id], queryFn: () => fetchAudit(id!), enabled: Boolean(id), refetchInterval: (state) => ['PENDING', 'RUNNING'].includes(state.state.data?.status ?? '') ? 1800 : false });
  const history = useQuery({ queryKey: ['audits', { leadId: query.data?.leadId }], queryFn: () => fetchAudits({ leadId: query.data!.leadId, pageSize: 20 }), enabled: Boolean(query.data?.leadId) });
  const rerun = useMutation({ mutationFn: () => rerunAudit(id!), onSuccess: async (audit) => { await qc.invalidateQueries({ queryKey: ['audits'] }); toast.success('New audit queued'); navigate(`/audits/${audit.id}`); }, onError: (error) => toast.error(getApiError(error)) });
  if (query.isLoading) return <div className="grid min-h-[520px] place-items-center"><LoaderCircle className="h-8 w-8 animate-spin text-violet-400" /></div>;
  if (query.isError || !query.data) return <div className="card p-10 text-center text-rose-300">{query.isError ? getApiError(query.error) : 'Audit not found.'}</div>;
  const audit = query.data;
  const previous = history.data?.data.find((candidate) => candidate.id !== audit.id && candidate.status === 'COMPLETED');
  return <div className="space-y-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-start"><Link to="/audits" className="w-fit rounded-xl border border-zinc-800 p-2.5 text-zinc-400 hover:bg-zinc-900"><ArrowLeft className="h-4 w-4" /></Link><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-3xl font-semibold tracking-tight">{audit.lead.businessName}</h2><AuditStatusBadge status={audit.status} /></div><a href={audit.url} target="_blank" rel="noreferrer" className="mt-2 block max-w-2xl truncate text-sm text-zinc-500 hover:text-violet-300">{audit.url} <ExternalLink className="inline h-3.5 w-3.5" /></a><p className="mt-1 text-xs text-zinc-600">Started {new Date(audit.createdAt).toLocaleString()}</p></div><button disabled={rerun.isPending || ['PENDING', 'RUNNING'].includes(audit.status)} onClick={() => rerun.mutate()} className="button-primary lg:ml-auto">{rerun.isPending ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}Re-run audit</button></div>
    {['PENDING', 'RUNNING'].includes(audit.status) && <ProgressCard status={audit.status} />}
    {audit.status === 'FAILED' && <AuditFailure reason={audit.failureReason} />}
    {audit.status === 'COMPLETED' && <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{scoreFields.map(([label, key]) => <ScoreCard key={key} label={label} value={audit[key]} delta={previous?.[key] == null || audit[key] == null ? null : audit[key]! - (previous?.[key] ?? 0)} primary={key === 'overallScore'} />)}</div>
      {previous && <p className="text-xs text-zinc-600">Score changes compare this audit with {new Date(previous.createdAt).toLocaleString()}.</p>}
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1.4fr)_minmax(340px,.6fr)]"><div className="space-y-6"><IssueGroups issues={audit.problems} /><RawMetrics metrics={audit.rawMetrics} /></div><aside className="space-y-6"><ListCard title="Strengths" icon={<CheckCircle2 className="h-4 w-4 text-emerald-400" />} items={audit.strengths} empty="No strong signals were detected in this run." /><ListCard title="Recommended improvements" icon={<Sparkles className="h-4 w-4 text-violet-400" />} items={audit.recommendedActions} ordered empty="No recommendations were generated." /><HistoryCard current={audit} audits={history.data?.data ?? []} /></aside></div></>}
  </div>;
}

function ProgressCard({ status }: { status: string }) { return <section className="card p-8"><div className="mx-auto max-w-xl text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-violet-500/10"><LoaderCircle className="h-7 w-7 animate-spin text-violet-400" /></div><h3 className="mt-5 text-lg font-semibold">{status === 'PENDING' ? 'Audit queued' : 'Website analysis in progress'}</h3><p className="mt-2 text-sm leading-6 text-zinc-500">The worker is validating the destination, fetching public website data, checking key categories, and saving the results. This page updates automatically.</p></div></section>; }
function ScoreCard({ label, value, delta, primary }: { label: string; value: number | null; delta: number | null; primary?: boolean }) { const tone = value == null ? 'text-zinc-500' : value >= 80 ? 'text-emerald-300' : value >= 60 ? 'text-amber-300' : 'text-rose-300'; return <section className={`card p-5 ${primary ? 'border-violet-500/30 bg-violet-500/5' : ''}`}><p className="text-xs uppercase tracking-wider text-zinc-600">{label}</p><div className="mt-3 flex items-end gap-2"><span className={`text-3xl font-semibold ${tone}`}>{value ?? '—'}</span>{value != null && <span className="mb-1 text-xs text-zinc-600">/100</span>}</div>{delta != null && delta !== 0 && <p className={`mt-2 flex items-center gap-1 text-xs ${delta > 0 ? 'text-emerald-400' : 'text-rose-400'}`}>{delta > 0 ? <TrendingUp className="h-3.5 w-3.5" /> : <TrendingDown className="h-3.5 w-3.5" />}{delta > 0 ? '+' : ''}{delta} since last</p>}</section>; }
function IssueGroups({ issues }: { issues: AuditIssue[] }) { return <section className="card p-6"><div className="mb-5 flex items-center gap-2"><ShieldAlert className="h-5 w-5 text-amber-400" /><h3 className="font-semibold">Issues by severity</h3><span className="ml-auto text-xs text-zinc-600">{issues.length} findings</span></div>{issues.length ? <div className="space-y-5">{severityOrder.map((severity) => { const rows = issues.filter((issue) => issue.severity === severity); return rows.length ? <div key={severity}><p className={`mb-2 text-xs font-semibold ${severityTone(severity)}`}>{severity} · {rows.length}</p><div className="space-y-2">{rows.map((issue, index) => <div key={`${issue.title}-${index}`} className="rounded-xl border border-zinc-800 bg-zinc-950/30 p-4"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{issue.title}</p><span className="rounded-full bg-zinc-800 px-2 py-0.5 text-[10px] text-zinc-500">{issue.category}</span></div><p className="mt-2 text-sm leading-6 text-zinc-500">{issue.description}</p><p className="mt-2 text-sm text-violet-300"><ArrowRight className="mr-1 inline h-3.5 w-3.5" />{issue.recommendation}</p></div>)}</div></div> : null; })}</div> : <p className="text-sm text-zinc-600">No issues were detected.</p>}</section>; }
function severityTone(severity: AuditSeverity) { return { CRITICAL: 'text-rose-400', HIGH: 'text-orange-400', MEDIUM: 'text-amber-400', LOW: 'text-sky-400', INFO: 'text-zinc-400' }[severity]; }
function ListCard({ title, icon, items, ordered, empty }: { title: string; icon: ReactNode; items: string[]; ordered?: boolean; empty: string }) { return <section className="card p-5"><h3 className="flex items-center gap-2 font-semibold">{icon}{title}</h3>{items.length ? <div className="mt-4 space-y-3">{items.map((item, index) => <div key={item} className="flex gap-3 text-sm leading-6 text-zinc-400"><span className="mt-0.5 grid h-5 min-w-5 place-items-center rounded-full bg-zinc-800 text-[10px] text-zinc-400">{ordered ? index + 1 : '✓'}</span><span>{item}</span></div>)}</div> : <p className="mt-4 text-sm text-zinc-600">{empty}</p>}</section>; }
function RawMetrics({ metrics }: { metrics: Record<string, unknown> }) { return <details className="card p-6"><summary className="flex cursor-pointer list-none items-center gap-2 font-semibold"><ChevronDown className="h-4 w-4 text-zinc-500" />Raw technical metrics</summary><pre className="mt-5 max-h-[560px] overflow-auto rounded-xl bg-zinc-950 p-4 text-xs leading-6 text-zinc-500">{JSON.stringify(metrics, null, 2)}</pre></details>; }
function HistoryCard({ current, audits }: { current: WebsiteAudit; audits: WebsiteAudit[] }) { return <section className="card p-5"><h3 className="flex items-center gap-2 font-semibold"><FileSearch className="h-4 w-4 text-violet-400" />Audit history</h3><div className="mt-4 space-y-2">{audits.map((audit) => <Link key={audit.id} to={`/audits/${audit.id}`} className={`flex items-center justify-between rounded-xl border p-3 text-sm ${audit.id === current.id ? 'border-violet-500/30 bg-violet-500/5' : 'border-zinc-800 hover:border-zinc-700'}`}><span>{new Date(audit.createdAt).toLocaleDateString()}</span><span className="text-zinc-500">{audit.overallScore == null ? audit.status : `${audit.overallScore}/100`}</span></Link>)}</div></section>; }
