import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Archive, ArrowLeft, BriefcaseBusiness, Calendar, ExternalLink, FileSearch, FileText, Globe2, LoaderCircle, Mail, MapPin, MessageSquareText, Pencil, Phone, UserRound } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type { ReactNode } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { archiveLead, fetchLead, updateLead } from '../features/leads/lead-api';
import { PriorityBadge, StatusBadge } from '../features/leads/lead-badges';
import { LEAD_PRIORITIES, LEAD_STATUSES, labelEnum, type LeadPriority, type LeadStatus } from '../features/leads/lead-types';
import { getApiError } from '../lib/api';
import { LeadAuditPanel } from '../features/audits/lead-audit-panel';

export function LeadDetailPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ['lead', id], queryFn: () => fetchLead(id!), enabled: Boolean(id) });
  const updateMutation = useMutation({
    mutationFn: (values: { status?: LeadStatus; priority?: LeadPriority }) => updateLead(id!, values),
    onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['lead', id] }), queryClient.invalidateQueries({ queryKey: ['leads'] })]); toast.success('Lead updated'); },
    onError: (error) => toast.error(getApiError(error)),
  });
  const archiveMutation = useMutation({
    mutationFn: () => archiveLead(id!),
    onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['leads'] }); toast.success('Lead archived'); navigate('/leads'); },
    onError: (error) => toast.error(getApiError(error)),
  });

  if (query.isLoading) return <div className="grid min-h-[520px] place-items-center"><LoaderCircle className="h-7 w-7 animate-spin text-violet-400" /></div>;
  if (query.isError || !query.data) return <div className="card p-10 text-center"><p className="font-medium text-rose-300">Lead unavailable</p><p className="mt-2 text-sm text-zinc-600">{query.isError ? getApiError(query.error) : 'This lead could not be found.'}</p><Link to="/leads" className="mt-5 inline-block text-sm text-violet-400">Back to leads</Link></div>;
  const lead = query.data;

  return <div className="space-y-6">
    <div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div className="flex items-start gap-4"><Link to="/leads" className="mt-1 rounded-xl border border-zinc-800 p-2.5 text-zinc-400 hover:bg-zinc-900"><ArrowLeft className="h-4 w-4" /></Link><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-3xl font-semibold tracking-tight">{lead.businessName}</h2>{lead.archivedAt && <span className="rounded-full border border-zinc-700 px-2.5 py-1 text-xs text-zinc-500">Archived</span>}</div><p className="mt-2 text-sm text-zinc-500">{lead.industry || 'Industry not set'}{lead.city || lead.country ? ` · ${[lead.city, lead.country].filter(Boolean).join(', ')}` : ''}</p><div className="mt-4 flex flex-wrap gap-2"><StatusBadge status={lead.status} /><span className="rounded-full border border-zinc-800 px-2.5 py-1"><PriorityBadge priority={lead.priority} /></span></div></div></div><div className="flex flex-wrap gap-2"><Link to={`/leads/${lead.id}/edit`} className="inline-flex items-center gap-2 rounded-xl border border-zinc-700 px-4 py-2.5 text-sm text-zinc-300 hover:bg-zinc-800"><Pencil className="h-4 w-4" />Edit</Link>{!lead.archivedAt && <button disabled={archiveMutation.isPending} onClick={() => { if (window.confirm(`Archive ${lead.businessName}?`)) archiveMutation.mutate(); }} className="inline-flex items-center gap-2 rounded-xl border border-rose-500/20 px-4 py-2.5 text-sm text-rose-300 hover:bg-rose-500/10"><Archive className="h-4 w-4" />Archive</button>}</div></div>

    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-6"><DetailSection title="Business information" icon={BriefcaseBusiness}><div className="grid gap-5 sm:grid-cols-2"><Detail label="Industry" value={lead.industry} /><Detail label="Source" value={lead.source} /><Detail label="Source reference" value={lead.sourceReference} /><Detail label="Created" value={new Date(lead.createdAt).toLocaleString()} /><div className="sm:col-span-2"><Detail label="Description" value={lead.description} multiline /></div></div></DetailSection>
      <DetailSection title="Contact information" icon={Mail}><div className="grid gap-4 sm:grid-cols-2"><LinkDetail label="Email" value={lead.email} href={lead.email ? `mailto:${lead.email}` : undefined} icon={Mail} /><LinkDetail label="Phone" value={lead.phone} href={lead.phone ? `tel:${lead.phone}` : undefined} icon={Phone} /><LinkDetail label="Website" value={lead.websiteUrl} href={lead.websiteUrl} icon={Globe2} /><LinkDetail label="Google Maps" value={lead.address || lead.googleMapsUrl} href={lead.googleMapsUrl} icon={MapPin} /></div></DetailSection>
      <DetailSection title="Business contacts" icon={UserRound}>{lead.contacts.length ? <div className="grid gap-3 sm:grid-cols-2">{lead.contacts.map((contact) => <div key={contact.id} className="rounded-xl border border-zinc-800 bg-zinc-950/40 p-4"><div className="flex items-center gap-2"><p className="font-medium">{contact.name}</p>{contact.isPrimary && <span className="rounded-full bg-violet-500/10 px-2 py-0.5 text-[10px] text-violet-300">Primary</span>}</div><p className="mt-1 text-xs text-zinc-600">{contact.jobTitle || 'Title not set'}</p><div className="mt-4 space-y-1 text-sm text-zinc-400">{contact.email && <a href={`mailto:${contact.email}`} className="block hover:text-violet-300">{contact.email}</a>}{contact.phone && <a href={`tel:${contact.phone}`} className="block hover:text-violet-300">{contact.phone}</a>}</div></div>)}</div> : <EmptyText text="No contacts have been added." />}</DetailSection>
      <DetailSection title="Notes" icon={FileText}>{lead.notes ? <p className="whitespace-pre-wrap text-sm leading-7 text-zinc-400">{lead.notes}</p> : <EmptyText text="No internal notes yet." />}</DetailSection>
      <div className="grid gap-4 md:grid-cols-3"><LeadAuditPanel leadId={lead.id} websiteUrl={lead.websiteUrl} /><HistoryPlaceholder icon={MessageSquareText} title="Outreach history" phase="Phase 7" /><HistoryPlaceholder icon={FileText} title="Proposal history" phase="Phase 9" /></div>
    </div><aside className="space-y-6"><section className="card p-5"><h3 className="font-semibold">Lead controls</h3><label className="mt-5 block"><span className="mb-2 block text-xs text-zinc-600">Status</span><select value={lead.status} disabled={updateMutation.isPending || Boolean(lead.archivedAt)} onChange={(event) => updateMutation.mutate({ status: event.target.value as LeadStatus })} className="input py-2.5">{LEAD_STATUSES.map((status) => <option key={status} value={status}>{labelEnum(status)}</option>)}</select></label><label className="mt-4 block"><span className="mb-2 block text-xs text-zinc-600">Priority</span><select value={lead.priority} disabled={updateMutation.isPending || Boolean(lead.archivedAt)} onChange={(event) => updateMutation.mutate({ priority: event.target.value as LeadPriority })} className="input py-2.5">{LEAD_PRIORITIES.map((priority) => <option key={priority} value={priority}>{labelEnum(priority)}</option>)}</select></label></section>
      <DetailSection title="Public profiles" icon={Globe2}><div className="space-y-2"><SocialLink label="Instagram" href={lead.instagramUrl} /><SocialLink label="Facebook" href={lead.facebookUrl} /><SocialLink label="LinkedIn" href={lead.linkedinUrl} /></div></DetailSection>
      <DetailSection title="Status history" icon={Calendar}>{lead.statusHistory?.length ? <div className="space-y-4">{lead.statusHistory.map((history) => <div key={history.id} className="relative border-l border-zinc-800 pl-4"><p className="text-sm text-zinc-300">{history.fromStatus ? `${labelEnum(history.fromStatus)} → ` : ''}{labelEnum(history.toStatus)}</p><p className="mt-1 text-xs text-zinc-600">{history.user.name} · {new Date(history.createdAt).toLocaleString()}</p></div>)}</div> : <EmptyText text="No status changes recorded." />}</DetailSection></aside></div>
  </div>;
}

function DetailSection({ title, icon: Icon, children }: { title: string; icon: LucideIcon; children: ReactNode }) { return <section className="card p-6"><div className="mb-5 flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-zinc-800 text-violet-300"><Icon className="h-4 w-4" /></div><h3 className="font-semibold">{title}</h3></div>{children}</section>; }
function Detail({ label, value, multiline }: { label: string; value?: string | null; multiline?: boolean }) { return <div><p className="text-xs text-zinc-600">{label}</p><p className={`mt-1 text-sm text-zinc-300 ${multiline ? 'whitespace-pre-wrap leading-6' : ''}`}>{value || '—'}</p></div>; }
function LinkDetail({ label, value, href, icon: Icon }: { label: string; value?: string | null; href?: string | null; icon: LucideIcon }) { return <div className="rounded-xl border border-zinc-800 bg-zinc-950/30 p-4"><p className="flex items-center gap-2 text-xs text-zinc-600"><Icon className="h-3.5 w-3.5" />{label}</p>{href ? <a href={href} target={href.startsWith('http') ? '_blank' : undefined} rel="noreferrer" className="mt-2 block truncate text-sm text-violet-300 hover:underline">{value}<ExternalLink className="ml-1 inline h-3 w-3" /></a> : <p className="mt-2 text-sm text-zinc-600">Not available</p>}</div>; }
function SocialLink({ label, href }: { label: string; href: string | null }) { return href ? <a href={href} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-zinc-800 px-3 py-2.5 text-sm text-zinc-400 hover:border-violet-500/30 hover:text-violet-300"><span>{label}</span><ExternalLink className="h-3.5 w-3.5" /></a> : <div className="flex items-center justify-between rounded-xl border border-zinc-900 px-3 py-2.5 text-sm text-zinc-700"><span>{label}</span><span className="text-xs">Missing</span></div>; }
function HistoryPlaceholder({ icon: Icon, title, phase }: { icon: LucideIcon; title: string; phase: string }) { return <div className="card p-5"><Icon className="h-5 w-5 text-zinc-600" /><h3 className="mt-4 text-sm font-medium">{title}</h3><p className="mt-1 text-xs text-zinc-600">Available in {phase}</p></div>; }
function EmptyText({ text }: { text: string }) { return <p className="text-sm text-zinc-600">{text}</p>; }
