import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, Check, Clock3, Database, ExternalLink, FileSpreadsheet, LoaderCircle, MapPin, Save, Search, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';
import type { UseFormRegisterReturn } from 'react-hook-form';
import type { LucideIcon } from 'lucide-react';
import type { ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';
import { z } from 'zod';
import { api, getApiError } from '../lib/api';

type ProviderId = 'MOCK' | 'GOOGLE_PLACES';
interface SearchValues { provider: ProviderId; keyword: string; category: string; country: string; city: string; radius?: number; latitude?: number; longitude?: number; minimumRating?: number; hasWebsite: string; hasPhone: string; hasEmail: string; maximumResults: number }
interface Provider { id: string; name: string; available: boolean; searchable: boolean; warning: string; importPath?: string }
interface Result { resultId: string; providerReference: string; businessName: string; address?: string; city?: string; country?: string; rating?: number; reviewCount?: number; websiteUrl?: string; phone?: string; email?: string; businessTypes: string[]; googleMapsUrl?: string; existingLeadId?: string; duplicateReasons: string[] }
interface Job { id: string; provider: ProviderId; criteria: Omit<SearchValues, 'provider'>; results: Result[]; status: string; totalResults: number; importedResults: number; duplicateResults: number; createdAt: string; errorDetails?: string }
interface Template { id: string; name: string; provider: ProviderId; criteria: Omit<SearchValues, 'provider'> }

const schema = z.object({ provider: z.enum(['MOCK', 'GOOGLE_PLACES']), keyword: z.string().trim().min(2, 'Enter a keyword'), category: z.string(), country: z.string(), city: z.string(), radius: z.number().min(100).max(50000).optional(), latitude: z.number().min(-90).max(90).optional(), longitude: z.number().min(-180).max(180).optional(), minimumRating: z.number().min(0).max(5).optional(), hasWebsite: z.string(), hasPhone: z.string(), hasEmail: z.string(), maximumResults: z.number().int().min(1).max(60) });
const defaults: SearchValues = { provider: 'MOCK', keyword: '', category: '', country: '', city: '', radius: undefined, latitude: undefined, longitude: undefined, minimumRating: undefined, hasWebsite: '', hasPhone: '', hasEmail: '', maximumResults: 20 };
const clean = (values: SearchValues) => Object.fromEntries(Object.entries(values).map(([key, value]) => [key, ['hasWebsite', 'hasPhone', 'hasEmail'].includes(key) ? value === '' ? undefined : value === 'true' : value === '' ? undefined : value]));
const criteriaOf = (values: SearchValues) => { const { provider: _provider, ...criteria } = clean(values) as unknown as SearchValues; return criteria; };

export function LeadFinderPage() {
  const qc = useQueryClient(); const [job, setJob] = useState<Job | null>(null); const [selected, setSelected] = useState<Set<string>>(new Set()); const [templateName, setTemplateName] = useState('');
  const form = useForm<SearchValues>({ resolver: zodResolver(schema), defaultValues: defaults });
  const providers = useQuery({ queryKey: ['finder-providers'], queryFn: async () => (await api.get<{ providers: Provider[] }>('/lead-finder/providers')).data.providers });
  const history = useQuery({ queryKey: ['finder-history'], queryFn: async () => (await api.get<{ jobs: Job[] }>('/lead-finder/history')).data.jobs });
  const templates = useQuery({ queryKey: ['finder-templates'], queryFn: async () => (await api.get<{ templates: Template[] }>('/lead-finder/templates')).data.templates });
  const usage = useQuery({ queryKey: ['finder-usage'], queryFn: async () => (await api.get<{ usage: Array<{ provider: string; calls: number; results: number }> }>('/lead-finder/usage')).data.usage });
  useEffect(() => { const first = providers.data?.find((provider) => provider.searchable && provider.available); if (first && !providers.data?.find((provider) => provider.id === form.getValues('provider'))?.available) form.setValue('provider', first.id as ProviderId); }, [providers.data, form]);

  const searchMutation = useMutation({ mutationFn: async (values: SearchValues) => (await api.post<{ job: Job; warnings: string[] }>('/lead-finder/search', clean(values))).data, onSuccess: (data) => { setJob(data.job); setSelected(new Set()); data.warnings.forEach((warning) => toast.info(warning)); void qc.invalidateQueries({ queryKey: ['finder-history'] }); void qc.invalidateQueries({ queryKey: ['finder-usage'] }); }, onError: (error) => toast.error(getApiError(error)) });
  const importMutation = useMutation({ mutationFn: async () => (await api.post<{ imported: number; duplicates: number }>(`/lead-finder/jobs/${job!.id}/import`, { resultIds: [...selected] })).data, onSuccess: (data) => { toast.success(`${data.imported} leads imported${data.duplicates ? `; ${data.duplicates} duplicates skipped` : ''}`); setSelected(new Set()); void qc.invalidateQueries({ queryKey: ['leads'] }); void qc.invalidateQueries({ queryKey: ['finder-history'] }); }, onError: (error) => toast.error(getApiError(error)) });
  const templateMutation = useMutation({ mutationFn: async () => api.post('/lead-finder/templates', { name: templateName, provider: form.getValues('provider'), criteria: criteriaOf(form.getValues()) }), onSuccess: () => { toast.success('Search template saved'); setTemplateName(''); void qc.invalidateQueries({ queryKey: ['finder-templates'] }); }, onError: (error) => toast.error(getApiError(error)) });
  const loadJob = async (id: string) => { try { const data = (await api.get<{ job: Job }>(`/lead-finder/jobs/${id}`)).data.job; setJob(data); setSelected(new Set()); } catch (error) { toast.error(getApiError(error)); } };
  const toggle = (id: string) => setSelected((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });
  const selectable = job?.results.filter((result) => !result.existingLeadId) ?? [];

  const number = { setValueAs: (value: string) => value === '' ? undefined : Number(value) };
  return <div className="space-y-6"><div><p className="text-sm font-medium text-violet-400">Approved data sources</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">Lead Finder</h2><p className="mt-2 text-sm text-zinc-500">Search public business data, review every result, then choose what to import.</p></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="space-y-6"><form onSubmit={form.handleSubmit((values) => searchMutation.mutate(values))} className="card p-6"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Field label="Provider"><select className="input" {...form.register('provider')}>{providers.data?.filter((p) => p.searchable).map((p) => <option key={p.id} value={p.id} disabled={!p.available}>{p.name}{!p.available ? ' — unavailable' : ''}</option>)}</select></Field><Field label="Keyword" error={form.formState.errors.keyword?.message}><input className="input" placeholder="web design prospects" {...form.register('keyword')} /></Field><Field label="Business category"><input className="input" placeholder="restaurant" {...form.register('category')} /></Field><Field label="Country"><input className="input" {...form.register('country')} /></Field><Field label="City"><input className="input" {...form.register('city')} /></Field><Field label="Minimum rating"><input className="input" type="number" step="0.1" {...form.register('minimumRating', number)} /></Field><Field label="Radius (meters)"><input className="input" type="number" {...form.register('radius', number)} /></Field><Field label="Center latitude"><input className="input" type="number" step="any" {...form.register('latitude', number)} /></Field><Field label="Center longitude"><input className="input" type="number" step="any" {...form.register('longitude', number)} /></Field><Field label="Website"><TriSelect register={form.register('hasWebsite')} /></Field><Field label="Phone"><TriSelect register={form.register('hasPhone')} /></Field><Field label="Email"><TriSelect register={form.register('hasEmail')} /></Field><Field label="Maximum results"><input className="input" type="number" {...form.register('maximumResults', number)} /></Field></div><div className="mt-5 flex flex-col gap-3 border-t border-zinc-800 pt-5 sm:flex-row sm:items-center"><p className="text-xs text-zinc-600">Radius is applied when latitude and longitude are provided.</p><button disabled={searchMutation.isPending} className="button-primary sm:ml-auto">{searchMutation.isPending ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />}{searchMutation.isPending ? 'Searching provider…' : 'Search businesses'}</button></div></form>
      {job && <section className="card overflow-hidden"><div className="flex flex-wrap items-center gap-3 border-b border-zinc-800 p-5"><div><h3 className="font-semibold">Search results</h3><p className="mt-1 text-xs text-zinc-600">{job.totalResults} found · {job.duplicateResults} already known</p></div><button onClick={() => setSelected(new Set(selectable.map((r) => r.resultId)))} className="ml-auto text-xs text-violet-400">Select all importable</button><button disabled={!selected.size || importMutation.isPending} onClick={() => importMutation.mutate()} className="button-primary py-2.5">{importMutation.isPending && <LoaderCircle className="h-4 w-4 animate-spin" />}Import selected ({selected.size})</button></div>{job.results.length ? <div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left"><thead className="bg-zinc-950/50 text-[11px] uppercase text-zinc-600"><tr><th className="p-4"></th><th className="p-4">Business</th><th className="p-4">Location</th><th className="p-4">Rating</th><th className="p-4">Contact</th><th className="p-4">Source status</th></tr></thead><tbody className="divide-y divide-zinc-800">{job.results.map((result) => <tr key={result.resultId} className="hover:bg-zinc-900/50"><td className="p-4"><input type="checkbox" checked={selected.has(result.resultId)} disabled={Boolean(result.existingLeadId)} onChange={() => toggle(result.resultId)} className="h-4 w-4 accent-violet-500" /></td><td className="p-4"><p className="font-medium">{result.businessName}</p><p className="mt-1 text-xs text-zinc-600">{result.businessTypes.slice(0, 2).join(', ')}</p></td><td className="p-4 text-sm text-zinc-500">{result.address || [result.city, result.country].filter(Boolean).join(', ') || '—'}</td><td className="p-4 text-sm text-zinc-400">{result.rating ? `${result.rating} (${result.reviewCount ?? 0})` : '—'}</td><td className="p-4 text-xs text-zinc-500">{result.websiteUrl && <a href={result.websiteUrl} target="_blank" rel="noreferrer" className="block text-violet-400">Website <ExternalLink className="inline h-3 w-3" /></a>}{result.phone || 'No phone'}{!result.email && <span className="block text-zinc-700">No provider email</span>}</td><td className="p-4">{result.existingLeadId ? <Link to={`/leads/${result.existingLeadId}`} className="rounded-full bg-amber-500/10 px-2 py-1 text-xs text-amber-300">Existing · {result.duplicateReasons.join(', ')}</Link> : <span className="rounded-full bg-emerald-500/10 px-2 py-1 text-xs text-emerald-300">New</span>}</td></tr>)}</tbody></table></div> : <div className="p-12 text-center text-sm text-zinc-600">No businesses matched these filters.</div>}</section>}
    </div><aside className="space-y-6"><Panel title="Providers" icon={Database}>{providers.data?.map((p) => <div key={p.id} className="mb-3 rounded-xl border border-zinc-800 p-3"><div className="flex items-center justify-between"><p className="text-sm font-medium">{p.name}</p><span className={`h-2 w-2 rounded-full ${p.available ? 'bg-emerald-400' : 'bg-zinc-700'}`} /></div><p className="mt-2 text-xs leading-5 text-zinc-600">{p.warning}</p>{p.importPath && <Link className="mt-2 inline-flex text-xs text-violet-400" to={p.importPath}><FileSpreadsheet className="mr-1 h-3.5 w-3.5" />Open importer</Link>}</div>)}</Panel>
      <Panel title="Saved templates" icon={Save}><div className="flex gap-2"><input value={templateName} onChange={(e) => setTemplateName(e.target.value)} className="input py-2" placeholder="Template name" /><button disabled={templateName.length < 2 || templateMutation.isPending} onClick={() => templateMutation.mutate()} className="rounded-lg bg-violet-600 px-3 text-white"><Save className="h-4 w-4" /></button></div><div className="mt-3 space-y-2">{templates.data?.map((template) => <div key={template.id} className="flex items-center gap-2 rounded-xl border border-zinc-800 p-3"><button onClick={() => form.reset({ ...defaults, ...template.criteria, provider: template.provider })} className="min-w-0 flex-1 text-left"><p className="truncate text-sm">{template.name}</p><p className="text-xs text-zinc-600">{template.provider}</p></button><button onClick={async () => { await api.delete(`/lead-finder/templates/${template.id}`); void qc.invalidateQueries({ queryKey: ['finder-templates'] }); }} className="text-zinc-600 hover:text-rose-400"><Trash2 className="h-4 w-4" /></button></div>)}</div></Panel>
      <Panel title="Search history" icon={Clock3}><div className="max-h-72 space-y-2 overflow-auto">{history.data?.map((item) => <button key={item.id} onClick={() => void loadJob(item.id)} className="w-full rounded-xl border border-zinc-800 p-3 text-left hover:border-violet-500/30"><div className="flex justify-between"><p className="truncate text-sm">{(item.criteria as { keyword?: string }).keyword || item.provider}</p><span className="text-[10px] text-zinc-600">{item.status}</span></div><p className="mt-1 text-xs text-zinc-600">{item.totalResults} results · {new Date(item.createdAt).toLocaleDateString()}</p></button>)}</div></Panel>
      <Panel title="API usage" icon={Check}>{usage.data?.length ? usage.data.map((row) => <div key={row.provider} className="flex justify-between border-b border-zinc-800 py-2 text-xs"><span className="text-zinc-500">{row.provider}</span><span>{row.calls} calls · {row.results} results</span></div>) : <p className="text-sm text-zinc-600">No provider usage yet.</p>}<div className="mt-3 flex gap-2 text-xs text-amber-300/70"><AlertTriangle className="h-4 w-4 shrink-0" />Costs are not estimated because pricing varies by account and requested fields.</div></Panel></aside></div>
  </div>;
}

function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label><span className="mb-1.5 block text-xs text-zinc-500">{label}</span>{children}{error && <span className="mt-1 block text-xs text-rose-400">{error}</span>}</label>; }
function TriSelect({ register }: { register: UseFormRegisterReturn }) { return <select className="input" {...register}><option value="">Either</option><option value="true">Required</option><option value="false">Must be missing</option></select>; }
function Panel({ title, icon: Icon, children }: { title: string; icon: LucideIcon; children: ReactNode }) { return <section className="card p-5"><h3 className="mb-4 flex items-center gap-2 font-semibold"><Icon className="h-4 w-4 text-violet-400" />{title}</h3>{children}</section>; }
