import { keepPreviousData, useQuery } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, BriefcaseBusiness, Filter, Grid2X2, List, Mail, MapPin, Plus, Search, SlidersHorizontal, Upload } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { getApiError } from '../lib/api';
import { fetchLeads } from '../features/leads/lead-api';
import { PriorityBadge, StatusBadge } from '../features/leads/lead-badges';
import { LEAD_PRIORITIES, LEAD_STATUSES, labelEnum, type Lead } from '../features/leads/lead-types';

interface Filters { status: string; priority: string; industry: string; country: string; city: string; source: string; hasWebsite: string; hasEmail: string; hasSocialMedia: string; createdFrom: string; createdTo: string; archived: string; sortBy: string; sortOrder: string }
const initialFilters: Filters = { status: '', priority: '', industry: '', country: '', city: '', source: '', hasWebsite: '', hasEmail: '', hasSocialMedia: '', createdFrom: '', createdTo: '', archived: 'active', sortBy: 'createdAt', sortOrder: 'desc' };

export function LeadsPage() {
  const [view, setView] = useState<'table' | 'cards'>('table');
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [searchDraft, setSearchDraft] = useState('');
  const [search, setSearch] = useState('');
  const [filters, setFilters] = useState(initialFilters);
  const [page, setPage] = useState(1);
  const params = { page, pageSize: 12, search: search || undefined, ...Object.fromEntries(Object.entries(filters).map(([key, value]) => [key, value || undefined])) };
  const query = useQuery({ queryKey: ['leads', params], queryFn: () => fetchLeads(params), placeholderData: keepPreviousData });

  const setFilter = (key: keyof Filters, value: string) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1); };
  const reset = () => { setFilters(initialFilters); setSearch(''); setSearchDraft(''); setPage(1); };
  const activeFilterCount = Object.entries(filters).filter(([key, value]) => value && value !== initialFilters[key as keyof Filters]).length;

  return <div className="space-y-6">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-sm font-medium text-violet-400">Lead management</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">Potential clients</h2><p className="mt-2 text-sm text-zinc-500">Review, qualify, and organize every acquisition opportunity.</p></div><div className="flex flex-wrap gap-2"><Link to="/leads/import" className="inline-flex items-center gap-2 rounded-xl border border-zinc-700 px-4 py-2.5 text-sm font-medium text-zinc-300 hover:bg-zinc-800"><Upload className="h-4 w-4" />Import CSV</Link><Link to="/leads/new" className="button-primary py-2.5"><Plus className="h-4 w-4" />New lead</Link></div></div>

    <section className="card overflow-hidden">
      <div className="flex flex-col gap-3 border-b border-zinc-800 p-4 lg:flex-row lg:items-center"><form onSubmit={(event) => { event.preventDefault(); setSearch(searchDraft); setPage(1); }} className="relative flex-1"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-600" /><input value={searchDraft} onChange={(event) => setSearchDraft(event.target.value)} className="input pl-11" placeholder="Search business, industry, email, or city…" /></form><button onClick={() => setFiltersOpen((current) => !current)} className={`inline-flex items-center justify-center gap-2 rounded-xl border px-4 py-3 text-sm ${filtersOpen || activeFilterCount ? 'border-violet-500/30 bg-violet-500/10 text-violet-300' : 'border-zinc-700 text-zinc-400 hover:bg-zinc-800'}`}><SlidersHorizontal className="h-4 w-4" />Filters{activeFilterCount > 0 && <span className="rounded-full bg-violet-500 px-1.5 text-[10px] text-white">{activeFilterCount}</span>}</button><div className="flex rounded-xl border border-zinc-800 p-1"><button aria-label="Table view" onClick={() => setView('table')} className={`rounded-lg p-2 ${view === 'table' ? 'bg-zinc-800 text-white' : 'text-zinc-600'}`}><List className="h-4 w-4" /></button><button aria-label="Card view" onClick={() => setView('cards')} className={`rounded-lg p-2 ${view === 'cards' ? 'bg-zinc-800 text-white' : 'text-zinc-600'}`}><Grid2X2 className="h-4 w-4" /></button></div></div>

      {filtersOpen && <div className="grid gap-4 border-b border-zinc-800 bg-zinc-950/50 p-5 sm:grid-cols-2 lg:grid-cols-4"><FilterSelect label="Status" value={filters.status} onChange={(value) => setFilter('status', value)} options={LEAD_STATUSES.map((value) => ({ value, label: labelEnum(value) }))} /><FilterSelect label="Priority" value={filters.priority} onChange={(value) => setFilter('priority', value)} options={LEAD_PRIORITIES.map((value) => ({ value, label: labelEnum(value) }))} /><FilterInput label="Industry" value={filters.industry} onChange={(value) => setFilter('industry', value)} /><FilterInput label="Country" value={filters.country} onChange={(value) => setFilter('country', value)} /><FilterInput label="City" value={filters.city} onChange={(value) => setFilter('city', value)} /><FilterInput label="Source" value={filters.source} onChange={(value) => setFilter('source', value)} /><FilterSelect label="Website" value={filters.hasWebsite} onChange={(value) => setFilter('hasWebsite', value)} options={[{ value: 'true', label: 'Has website' }, { value: 'false', label: 'No website' }]} /><FilterSelect label="Email" value={filters.hasEmail} onChange={(value) => setFilter('hasEmail', value)} options={[{ value: 'true', label: 'Has email' }, { value: 'false', label: 'No email' }]} /><FilterSelect label="Social media" value={filters.hasSocialMedia} onChange={(value) => setFilter('hasSocialMedia', value)} options={[{ value: 'true', label: 'Has social profile' }, { value: 'false', label: 'No social profile' }]} /><FilterSelect label="Archive" value={filters.archived} onChange={(value) => setFilter('archived', value)} allowEmpty={false} options={[{ value: 'active', label: 'Active leads' }, { value: 'archived', label: 'Archived leads' }, { value: 'all', label: 'All leads' }]} /><FilterInput label="Created from" type="date" value={filters.createdFrom} onChange={(value) => setFilter('createdFrom', value)} /><FilterInput label="Created to" type="date" value={filters.createdTo} onChange={(value) => setFilter('createdTo', value)} /><FilterSelect label="Sort by" value={filters.sortBy} onChange={(value) => setFilter('sortBy', value)} allowEmpty={false} options={[{ value: 'createdAt', label: 'Created date' }, { value: 'updatedAt', label: 'Updated date' }, { value: 'businessName', label: 'Business name' }, { value: 'status', label: 'Status' }, { value: 'priority', label: 'Priority' }]} /><FilterSelect label="Direction" value={filters.sortOrder} onChange={(value) => setFilter('sortOrder', value)} allowEmpty={false} options={[{ value: 'desc', label: 'Descending' }, { value: 'asc', label: 'Ascending' }]} /><div className="flex items-end"><button onClick={reset} className="w-full rounded-xl border border-zinc-800 px-3 py-2.5 text-sm text-zinc-500 hover:text-white">Clear filters</button></div></div>}

      {query.isLoading ? <LoadingRows /> : query.isError ? <ErrorState message={getApiError(query.error)} retry={() => void query.refetch()} /> : !query.data?.data.length ? <EmptyState filtered={Boolean(search || activeFilterCount)} reset={reset} /> : view === 'table' ? <LeadTable leads={query.data.data} /> : <LeadCards leads={query.data.data} />}
      {query.data && query.data.data.length > 0 && <div className="flex flex-col gap-3 border-t border-zinc-800 px-5 py-4 text-sm sm:flex-row sm:items-center"><p className="text-zinc-600">Showing {(query.data.pagination.page - 1) * query.data.pagination.pageSize + 1}–{Math.min(query.data.pagination.page * query.data.pagination.pageSize, query.data.pagination.total)} of {query.data.pagination.total}</p><div className="ml-auto flex items-center gap-2"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="rounded-lg border border-zinc-800 p-2 text-zinc-400 disabled:opacity-30"><ArrowLeft className="h-4 w-4" /></button><span className="px-2 text-xs text-zinc-500">Page {page} of {query.data.pagination.totalPages}</span><button disabled={page >= query.data.pagination.totalPages} onClick={() => setPage((value) => value + 1)} className="rounded-lg border border-zinc-800 p-2 text-zinc-400 disabled:opacity-30"><ArrowRight className="h-4 w-4" /></button></div></div>}
    </section>
  </div>;
}

function LeadTable({ leads }: { leads: Lead[] }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="border-b border-zinc-800 bg-zinc-950/40 text-[11px] uppercase tracking-wider text-zinc-600"><tr><th className="px-5 py-3 font-medium">Business</th><th className="px-5 py-3 font-medium">Location</th><th className="px-5 py-3 font-medium">Contact</th><th className="px-5 py-3 font-medium">Status</th><th className="px-5 py-3 font-medium">Priority</th><th className="px-5 py-3 font-medium"></th></tr></thead><tbody className="divide-y divide-zinc-800/80">{leads.map((lead) => <tr key={lead.id} className="transition hover:bg-zinc-900/60"><td className="px-5 py-4"><Link to={`/leads/${lead.id}`} className="font-medium hover:text-violet-300">{lead.businessName}</Link><p className="mt-1 text-xs text-zinc-600">{lead.industry || 'Industry not set'}</p></td><td className="px-5 py-4 text-sm text-zinc-500">{[lead.city, lead.country].filter(Boolean).join(', ') || '—'}</td><td className="px-5 py-4 text-sm text-zinc-500">{lead.email || lead.phone || '—'}</td><td className="px-5 py-4"><StatusBadge status={lead.status} /></td><td className="px-5 py-4"><PriorityBadge priority={lead.priority} /></td><td className="px-5 py-4 text-right"><Link to={`/leads/${lead.id}`} className="text-xs font-medium text-violet-400 hover:text-violet-300">View</Link></td></tr>)}</tbody></table></div>;
}

function LeadCards({ leads }: { leads: Lead[] }) {
  return <div className="grid gap-4 p-5 sm:grid-cols-2 xl:grid-cols-3">{leads.map((lead) => <Link to={`/leads/${lead.id}`} key={lead.id} className="rounded-2xl border border-zinc-800 bg-zinc-950/40 p-5 transition hover:-translate-y-0.5 hover:border-violet-500/30"><div className="flex items-start justify-between gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-zinc-800 text-violet-300"><BriefcaseBusiness className="h-5 w-5" /></div><PriorityBadge priority={lead.priority} /></div><h3 className="mt-5 font-semibold">{lead.businessName}</h3><p className="mt-1 text-xs text-zinc-600">{lead.industry || 'Industry not set'}</p><div className="mt-5 space-y-2 text-xs text-zinc-500"><p className="flex items-center gap-2"><MapPin className="h-3.5 w-3.5" />{[lead.city, lead.country].filter(Boolean).join(', ') || 'Location not set'}</p><p className="flex items-center gap-2"><Mail className="h-3.5 w-3.5" />{lead.email || 'Email not set'}</p></div><div className="mt-5"><StatusBadge status={lead.status} /></div></Link>)}</div>;
}

function FilterInput({ label, type = 'text', value, onChange }: { label: string; type?: string; value: string; onChange: (value: string) => void }) { return <label><span className="mb-1.5 block text-xs text-zinc-600">{label}</span><input type={type} className="input py-2.5" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function FilterSelect({ label, value, options, onChange, allowEmpty = true }: { label: string; value: string; options: Array<{ value: string; label: string }>; onChange: (value: string) => void; allowEmpty?: boolean }) { return <label><span className="mb-1.5 block text-xs text-zinc-600">{label}</span><select className="input py-2.5" value={value} onChange={(event) => onChange(event.target.value)}>{allowEmpty && <option value="">Any</option>}{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
function LoadingRows() { return <div className="space-y-3 p-5">{Array.from({ length: 6 }, (_, index) => <div key={index} className="h-16 animate-pulse rounded-xl bg-zinc-800/50" />)}</div>; }
function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div className="grid min-h-80 place-items-center p-8 text-center"><div><p className="font-medium text-rose-300">Could not load leads</p><p className="mt-2 text-sm text-zinc-600">{message}</p><button onClick={retry} className="mt-5 rounded-xl border border-zinc-700 px-4 py-2 text-sm">Try again</button></div></div>; }
function EmptyState({ filtered, reset }: { filtered: boolean; reset: () => void }) { return <div className="grid min-h-96 place-items-center p-8 text-center"><div className="max-w-sm"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-zinc-800 text-zinc-500"><Filter className="h-6 w-6" /></div><h3 className="mt-5 font-semibold">{filtered ? 'No matching leads' : 'No leads yet'}</h3><p className="mt-2 text-sm leading-6 text-zinc-600">{filtered ? 'Try adjusting the search or filters.' : 'Create a lead manually or import a reviewed CSV file.'}</p>{filtered ? <button onClick={reset} className="mt-5 text-sm font-medium text-violet-400">Clear filters</button> : <Link to="/leads/new" className="button-primary mt-5 py-2.5"><Plus className="h-4 w-4" />Create first lead</Link>}</div></div>; }
